"""The per-frame garment penetration report (work-order "glTF villager body",
final state 6): for EVERY frame of EVERY exported clip and for every age/sex
corner and build extreme, every garment is skinned with the body exactly as the
game skins it (same weights, same morphs, same skeleton), and each garment
vertex's depth inside the body is measured against the skinned body's surface
(nearest point, signed along its normal; a point that deep is counted inside
only when the body's winding number round it says so, fit.py `inside`). The skinning is the GAME'S path
(gamepath.py): the corner's mesh hung and baked, then skinned by the hung
bones; a gait's frames also at the shortest and longest stride the game warps
it to; each garment with its per-frame baked
offsets (resolve.py). The report lists, per garment, the
deepest penetration and where; the pipeline fails the penetration step when any
depth exceeds VILLAGER_ASSET.garmentPenetrationTolerance.

Written to verification/villager-body/penetration-report.md (and .json).
"""
import json
import os

import numpy as np

import gamepath as GP
import resolve as RS
import rig
from body import top4
from export import EXPORT_CLIPS
from fit import depths, garment_pos
from sheets import corner_weights, morphed

CORNERS = [(s, a, 0.0) for s in ('male', 'female') for a in ('child', 'youth', 'adult', 'elder')] + [('male', 'adult', -1.0), ('male', 'adult', 1.0)]


def measure(body, clips, garments, cfg, stride=1, names=None, clip_names=None, corners=None, log=print):
    from mathutils.bvhtree import BVHTree
    tol = cfg['VILLAGER_ASSET']['garmentPenetrationTolerance']
    jidx, jw = top4(body['W'])
    gnames = names or [n for n in garments['meshes'] if n.startswith('g-')]
    gskin = {n: top4(garments['meshes'][n]['W']) for n in gnames}
    worst = {n: {'depth': 0.0, 'at': None, 'over': 0, 'checked': 0} for n in gnames}
    for (sex, age, build) in (corners or CORNERS):
        w = corner_weights(sex, age, build)
        pos, j = morphed(body, w)
        person = GP.Person(j)
        bh = person.bake(pos, jidx, jw)
        gh = {n: person.bake(garment_pos(garments['meshes'][n], w), *gskin[n]) for n in gnames}
        for k, (cname, f, kst, q, hips) in enumerate(GP.poses(clips, clip_names or EXPORT_CLIPS, cfg)):
            if k % stride:
                continue
            pk = k if clip_names is None else None
            wr, wp = rig.fk(j, GP.stride_pose(person.h, q, hips, kst), hips)
            bv = person.skin(bh, jidx, jw, wr, wp)
            tree = BVHTree.FromPolygons(bv.tolist(), body['tris'].tolist(), all_triangles=True)
            for n in gnames:
                gb = gh[n]
                ro = None if pk is None else RS.person_offsets(garments['meshes'][n], w, pk)
                if ro is not None:
                    gb = gb.copy()
                    gb[ro[0]] += ro[1]
                gv = person.skin(gb, *gskin[n], wr, wp)
                d, _co, _n = depths(tree, gv, tol)
                deepest = max(0.0, float(d.max()))
                over = int((d > tol).sum())
                r = worst[n]
                r['checked'] += 1
                r['over'] += 1 if over else 0
                if deepest > r['depth']:
                    r['depth'] = deepest
                    r['at'] = f'{cname} frame {f}{"" if kst == 1 else f" stride {kst:g}"} ({sex} {age} build {build:+.0f})'
        log(f'penetration: {sex} {age} {build:+.0f} done')
    return worst, tol


def report(out, body, clips, garments, cfg, stride=1):
    worst, tol = measure(body, clips, garments, cfg, stride)
    frames = sum(1 for _ in GP.poses(clips, EXPORT_CLIPS, cfg))
    lines = [
        '# Garment penetration report',
        '',
        f'Generated by `node scripts/villager/build.mjs` (step `penetration`). Every frame of the clips {", ".join(EXPORT_CLIPS)} '
        f'({frames} poses: every frame, a gait\'s at strides {", ".join(f"{k:g}" for k in GP.strides(cfg))}{"" if stride == 1 else f"; every {stride}th"}), at {len(CORNERS)} body corners (both sexes × four age groups, and the adult man at build −1 and +1); '
        f'each garment alone on the body with its per-frame baked offsets (scripts/villager/resolve.py), skinned along the game\'s own path (the hung, baked mesh skinned by the hung bones; scripts/villager/gamepath.py). Depth = how far a garment vertex lies inside the skinned body '
        f'(figure units; 1 unit ≈ 1.3 m). Tolerance (VILLAGER_ASSET.garmentPenetrationTolerance): {tol}.',
        '',
        '| Garment | Deepest | Where | Frames over tolerance |',
        '| --- | --- | --- | --- |',
    ]
    bad = 0
    for n, r in sorted(worst.items()):
        ok = r['depth'] <= tol
        bad += 0 if ok else 1
        lines.append(f'| `{n}` | {r["depth"]:.4f}{"" if ok else " ✗"} | {r["at"] or "—"} | {r["over"]} / {r["checked"]} |')
    lines += ['', f'**{len(worst) - bad} of {len(worst)} garments within tolerance in every frame.**', '']
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'penetration-report.md'), 'w').write('\n'.join(lines))
    json.dump({'tolerance': tol, 'stride': stride, 'garments': worst}, open(os.path.join(out, 'penetration-report.json'), 'w'), indent=1)
    print('\n'.join(lines))
    return bad
