"""The per-frame garment penetration report (work-order "glTF villager body",
final state 6): for EVERY frame of EVERY exported clip and for every age/sex
corner and build extreme, every garment is skinned with the body exactly as the
game skins it (same weights, same morphs, same skeleton), and each garment
vertex's depth inside the body is measured against the skinned body's surface
(nearest point, signed along its normal). The report lists, per garment, the
deepest penetration and where; the pipeline fails the penetration step when any
depth exceeds VILLAGER_ASSET.garmentPenetrationTolerance.

Written to verification/villager-body/penetration-report.md (and .json).
"""
import json
import os

import numpy as np

import rig
from body import top4
from export import EXPORT_CLIPS
from fit import garment_pos, nearest
from sheets import corner_weights, morphed

CORNERS = [(s, a, 0.0) for s in ('male', 'female') for a in ('child', 'youth', 'adult', 'elder')] + [('male', 'adult', -1.0), ('male', 'adult', 1.0)]


def measure(body, clips, garments, cfg, stride=1, names=None, clip_names=None, corners=None, log=print):
    from mathutils.bvhtree import BVHTree
    tol = cfg['VILLAGER_ASSET']['garmentPenetrationTolerance']
    jidx, jw = top4(body['W'])
    gnames = names or [n for n in garments['meshes'] if n.startswith('g-')]
    gskin = {n: top4(garments['meshes'][n]['W']) for n in gnames}
    worst = {n: {'depth': 0.0, 'at': None, 'over': 0, 'checked': 0} for n in gnames}
    for (sex, age, build) in (corners or CORNERS):
        w = corner_weights(sex, age, build)
        pos, j = morphed(body, w)
        gpos = {n: garment_pos(garments['meshes'][n], w) for n in gnames}
        for cname in (clip_names or EXPORT_CLIPS):
            c = clips['clips'][cname]
            for f in range(0, len(c['times']), stride):
                wr, wp = rig.fk(j, c['q'][f], c['hips'][f])
                bv = rig.skin(pos, jidx, jw, j, wr, wp)
                tree = BVHTree.FromPolygons(bv.tolist(), body['tris'].tolist(), all_triangles=True)
                for n in gnames:
                    gi, gw = gskin[n]
                    gv = rig.skin(gpos[n], gi, gw, j, wr, wp)
                    co, nrm = nearest(tree, gv)
                    d = -np.einsum('ij,ij->i', gv - co, nrm)
                    deepest = max(0.0, float(d.max()))
                    over = int((d > tol).sum())
                    r = worst[n]
                    r['checked'] += 1
                    r['over'] += 1 if over else 0
                    if deepest > r['depth']:
                        r['depth'] = deepest
                        r['at'] = f'{cname} frame {f} ({sex} {age} build {build:+.0f})'
        log(f'penetration: {sex} {age} {build:+.0f} done')
    return worst, tol


def report(out, body, clips, garments, cfg, stride=1):
    worst, tol = measure(body, clips, garments, cfg, stride)
    frames = sum(len(clips['clips'][c]['times']) for c in EXPORT_CLIPS)
    lines = [
        '# Garment penetration report',
        '',
        f'Generated by `node scripts/villager/build.mjs` (step `penetration`). Every frame of the clips {", ".join(EXPORT_CLIPS)} '
        f'({frames} frames{"" if stride == 1 else f", every {stride}th"}), at {len(CORNERS)} body corners (both sexes × four age groups, and the adult man at build −1 and +1); '
        f'each garment alone on the body, skinned exactly as in the game. Depth = how far a garment vertex lies inside the skinned body '
        f'(figure units; 1 unit ≈ 1.3 m). Tolerance (VILLAGER_ASSET.garmentPenetrationTolerance): {tol}.',
        '',
        '| Garment | Deepest | Where | Frames over tolerance |',
        '| --- | --- | --- | --- |',
    ]
    bad = 0
    for n, r in sorted(worst.items()):
        ok = r['depth'] <= tol
        bad += 0 if ok else 1
        lines.append(f'| `{n}` | {r["depth"]:.4f}{"" if ok else " ✗"} | {r["at"] or "—"} | {r["over"]} / {r["checked"]} |')
    lines += ['', f'**{len(worst) - bad} of {len(worst)} garments within tolerance in every frame.**', '']
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'penetration-report.md'), 'w').write('\n'.join(lines))
    json.dump({'tolerance': tol, 'stride': stride, 'garments': worst}, open(os.path.join(out, 'penetration-report.json'), 'w'), indent=1)
    print('\n'.join(lines))
    return bad
