// A PINNED, HEADLESS BLENDER FOR THE ASSET PIPELINE — one idempotent command.
//
//   node scripts/blender.mjs install          install (a no-op when present)
//   node scripts/blender.mjs status           say what is installed where
//   node scripts/blender.mjs run <py> [args]  `blender -b --factory-startup --python <py> -- args`
//
// Blender is NEVER a build or runtime dependency: the game builds and runs
// from the committed .glb files alone; Blender only REPRODUCES them
// (tools/villager/). User authorization 04.10.2026: the author downloads,
// installs and configures it in the container, no user hand involved.
//
// WHY THE DEBIAN PACKAGE: this container reaches deb.debian.org but not
// download.blender.org (measured 05.10.2026), and the Debian archive is signed —
// `apt-get download` checks every file against the signed index. The pinned
// package and its dependency closure are UNPACKED (dpkg-deb -x, no root, no
// system change) into the main checkout's git-ignored `local/tools/`, shared
// by every worktree, and run through a wrapper that points the loader, Python
// and Blender's own scripts at that prefix.
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync, chmodSync, renameSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { join, resolve } from 'node:path'
import { mainCheckoutFrom } from './main-checkout-core.mjs'
import { isMainModule } from './is-main.mjs'

/** The pinned Blender (Debian bookworm). Changing it re-installs. */
export const BLENDER_PACKAGE = 'blender'
export const BLENDER_VERSION = '3.4.1+dfsg-2+b1'
/** Packages the pipeline needs beyond Blender's own closure (the glTF
 *  exporter imports numpy). */
export const EXTRA_PACKAGES = ['python3-numpy']

function sh(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', maxBuffer: 64 << 20, ...opts })
  if (r.status !== 0 && !opts.allowFail) {
    throw new Error(`${cmd} ${args.join(' ')} failed (${r.status}):\n${r.stderr || r.stdout}`)
  }
  return r
}

/** The main checkout (shared by every worktree), else this one. */
export function mainRoot(cwd = process.cwd()) {
  const top = sh('git', ['rev-parse', '--show-toplevel'], { cwd }).stdout.trim()
  const common = sh('git', ['rev-parse', '--path-format=absolute', '--git-common-dir'], { cwd }).stdout.trim()
  return mainCheckoutFrom(common, top) ?? top
}

export function installDir(root = mainRoot()) {
  return join(root, 'local', 'tools', `blender-${BLENDER_VERSION.replace(/[^A-Za-z0-9.+-]/g, '_')}`)
}

/** The wrapper every caller runs. */
export const wrapperPath = (dir) => join(dir, 'blender')

/**
 * The package names to fetch: Blender's closure as apt resolves it against THIS
 * host (the container image every session shares), plus the Python runtime
 * Blender's interpreter must find under the prefix.
 */
export function packageClosure() {
  const want = [`${BLENDER_PACKAGE}=${BLENDER_VERSION}`, ...EXTRA_PACKAGES]
  const r = sh('apt-get', ['install', '-s', '--no-install-recommends', '-o', 'Debug::NoLocking=1', ...want])
  const names = new Set()
  for (const line of r.stdout.split('\n')) {
    const m = /^Inst (\S+)/.exec(line)
    if (m) names.add(m[1])
  }
  for (const n of ['libpython3.11-stdlib', 'libpython3.11-minimal', 'python3.11-minimal', 'libpython3.11']) names.add(n)
  return [...names].sort()
}

/** Every directory under the prefix that holds a shared library (Debian keeps
 *  some in subdirectories — pulseaudio/, blas/, lapack/ — reached by
 *  alternatives symlinks or rpaths the prefix does not have). */
function libraryDirs(root) {
  const out = []
  const walk = (d) => {
    let has = false
    for (const e of readdirSync(d, { withFileTypes: true })) {
      if (e.isDirectory()) {
        if (!/python3|share|include|bin$/.test(e.name)) walk(join(d, e.name))
      } else if (/\.so(\.|$)/.test(e.name)) has = true
    }
    if (has) out.push(d)
  }
  for (const top of ['usr/lib/x86_64-linux-gnu', 'lib/x86_64-linux-gnu', 'usr/lib']) if (existsSync(join(root, top))) walk(join(root, top))
  return [...new Set(out)]
}

function writeWrapper(dir) {
  const lib = libraryDirs(join(dir, 'root'))
  const script = `#!/bin/sh
# Generated by scripts/blender.mjs — runs the unpacked pinned Blender headless.
R="${join(dir, 'root')}"
export LD_LIBRARY_PATH="${lib.join(':')}\${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONHOME="$R/usr"
export PYTHONPATH="$R/usr/lib/python3/dist-packages"
export BLENDER_SYSTEM_SCRIPTS="$R/usr/share/blender/scripts"
export BLENDER_SYSTEM_DATAFILES="$R/usr/share/blender/datafiles"
export BLENDER_USER_CONFIG="${join(dir, 'user', 'config')}"
export BLENDER_USER_SCRIPTS="${join(dir, 'user', 'scripts')}"
exec "$R/usr/bin/blender" "$@"
`
  writeFileSync(wrapperPath(dir), script)
  chmodSync(wrapperPath(dir), 0o755)
}

/** `blender --version`'s first line, or null when it does not run. */
export function probe(dir) {
  if (!existsSync(wrapperPath(dir))) return null
  const r = spawnSync(wrapperPath(dir), ['-b', '--factory-startup', '--version'], { encoding: 'utf8' })
  const line = (r.stdout || '').split('\n').find((l) => /^Blender \d/.test(l))
  return r.status === 0 && line ? line.trim() : null
}

export function install({ log = console.log } = {}) {
  const dir = installDir()
  const have = probe(dir)
  if (have) {
    log(`blender: already installed — ${have} at ${dir} (no-op)`)
    return dir
  }
  const tmp = `${dir}.partial`
  rmSync(tmp, { recursive: true, force: true })
  const debs = join(tmp, 'debs')
  mkdirSync(debs, { recursive: true })
  const pkgs = packageClosure()
  log(`blender: fetching ${pkgs.length} signed Debian packages for ${BLENDER_PACKAGE} ${BLENDER_VERSION}…`)
  sh('apt-get', ['download', '-o', 'Debug::NoLocking=1', ...pkgs.map((p) => (p === BLENDER_PACKAGE ? `${p}=${BLENDER_VERSION}` : p))], { cwd: debs })
  const root = join(tmp, 'root')
  mkdirSync(root, { recursive: true })
  for (const f of readdirSync(debs).filter((f) => f.endsWith('.deb'))) sh('dpkg-deb', ['-x', join(debs, f), root])
  rmSync(debs, { recursive: true, force: true })
  mkdirSync(join(tmp, 'user', 'config'), { recursive: true })
  mkdirSync(join(tmp, 'user', 'scripts'), { recursive: true })
  rmSync(dir, { recursive: true, force: true })
  renameSync(tmp, dir)
  writeWrapper(dir)
  const v = probe(dir)
  if (!v) throw new Error(`blender: unpacked to ${dir} but it does not run — see \`${wrapperPath(dir)} -b --version\``)
  log(`blender: installed — ${v} at ${dir}`)
  return dir
}

export function run(args) {
  const dir = installDir()
  if (!probe(dir)) install()
  const [py, ...rest] = args
  if (!py) throw new Error('usage: node scripts/blender.mjs run <script.py> [args…]')
  const r = spawnSync(wrapperPath(dir), ['-b', '--factory-startup', '--python-exit-code', '1', '--python', resolve(py), '--', ...rest], {
    stdio: 'inherit',
  })
  return r.status ?? 1
}

if (isMainModule(import.meta.url)) {
  const [cmd, ...rest] = process.argv.slice(2)
  try {
    if (cmd === 'install') install()
    else if (cmd === 'status') {
      const dir = installDir()
      console.log(`blender ${BLENDER_VERSION}: ${probe(dir) ?? 'NOT INSTALLED'} — ${dir}`)
    } else if (cmd === 'run') process.exitCode = run(rest)
    else {
      console.error('usage: node scripts/blender.mjs install | status | run <script.py> [args…]')
      process.exitCode = 2
    }
  } catch (e) {
    console.error(String(e?.message ?? e))
    process.exitCode = 1
  }
}
