// ONE INDEX OVER EVERY REPOSITORY COMMAND — the pure half of scripts/help.mjs.
//
// Descriptions and usage stay where they are already maintained: in each
// script's leading comment and `usage:` strings. This module only harvests and
// renders them, so the generated document can never become a second authority.

const cleanCommentLine = (line) => line
  .replace(/^\s*\/\/\s?/, '')
  .replace(/^\s*\/\*+\s?/, '')
  .replace(/^\s*\*\/?\s?/, '')
  .trim()

/** One sentence from the script's leading comment block. */
export function leadingPurpose(source, name = '') {
  const lines = String(source).replace(/^#![^\n]*\n/, '').split(/\r?\n/)
  const paragraph = []
  let began = false
  for (const line of lines) {
    if (!began && line.trim() === '') continue
    const comment = /^\s*(?:\/\/|\/\*|\*)/.test(line)
    if (!comment) break
    const cleaned = cleanCommentLine(line)
    if (!cleaned || cleaned === '/') {
      if (began) break
      continue
    }
    began = true
    paragraph.push(cleaned)
  }
  const text = paragraph.join(' ').replace(/\s+/g, ' ').trim()
  const sentence = /^(.+?[.!?])(?:\s|$)/.exec(text)?.[1] ?? text
  return sentence || `Tests and support for ${name.replace(/\.mjs$/, '')}.`
}

/** Every greppable usage line, kept in source order. */
export function usageLines(source) {
  const out = []
  for (const line of String(source).split(/\r?\n/)) {
    const at = line.toLowerCase().indexOf('usage:')
    if (at < 0) continue
    const usage = line.slice(at).trim().replace(/\\n/g, ' ').replace(/\s+/g, ' ')
    if (usage && !out.includes(usage)) out.push(usage)
  }
  return out
}

/** Parsed entries from [{ name, source }], sorted once for stable output. */
export function harvestCommands(files = []) {
  return files
    .filter((file) => file?.name?.endsWith('.mjs'))
    .map(({ name, source }) => ({ name, purpose: leadingPurpose(source, name), usages: usageLines(source) }))
    .sort((a, b) => a.name.localeCompare(b.name))
}

const escapeCell = (value) => String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ')

/** The committed projection. Regenerating from the tree must be byte-identical. */
export function renderCommandIndex(entries = []) {
  const rows = entries.map((entry) => {
    const usage = entry.usages.length ? entry.usages.join('<br>') : '—'
    return `| \`${escapeCell(entry.name)}\` | ${escapeCell(entry.purpose)} | ${escapeCell(usage)} |`
  })
  return [
    '<!-- Generated by `node scripts/help.mjs --write`; do not edit by hand. -->',
    '# Command index',
    '',
    `${entries.length} scripts. Purpose and usage are harvested from the scripts themselves.`,
    '',
    '| Script | Purpose | Usage |',
    '| --- | --- | --- |',
    ...rows,
    '',
  ].join('\n')
}

const words = (value) => String(value).toLowerCase().match(/[a-z0-9]+/g) ?? []

/** Best topic matches, weighted toward executable usage text. */
export function findCommands(entries = [], topic = '') {
  const terms = [...new Set(words(topic).filter((word) => word.length > 2))]
  if (!terms.length) return []
  return entries
    .map((entry) => {
      const name = entry.name.toLowerCase()
      const purpose = entry.purpose.toLowerCase()
      const usage = entry.usages.join(' ').toLowerCase()
      const score = terms.reduce((sum, term) =>
        sum + (name.includes(term) ? 4 : 0) + (usage.includes(term) ? 3 : 0) + (purpose.includes(term) ? 1 : 0), 0)
      return { ...entry, score }
    })
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))
}
